# Generated by Django 3.1.4 on 2020-12-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('property', models.TextField(default=0, max_length=1000, verbose_name='Характеристики')),
                ('preview', models.ImageField(null=True, upload_to='product_preview', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(default=0, help_text='Укажите цену', verbose_name='Цена')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во на складе')),
                ('prod_country', models.CharField(help_text='Введите страну производителя', max_length=50, verbose_name='Страна производитель')),
                ('release_year', models.IntegerField(default=0, help_text='Введите год релиза', verbose_name='Год релиза')),
                ('model_type', models.CharField(help_text='Введите модель', max_length=20, verbose_name='Модель товара')),
                ('guarantee', models.IntegerField(default=0, help_text='Введите гарантию на товар', verbose_name='Гарантия')),
                ('url', models.SlugField(default=0, max_length=160, unique=True)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
